#!/bin/bash
mkdir -p /var/www/vhosts/soludents/public/
cd /var/www/vhosts/soludents/public/frontend
npm install -unsafe-perm=true &
sleep 1m
npm start &
cd /var/www/vhosts/soludents/public/backend
npm install -unsafe-perm=true &
sleep 1m
forever start -a -l /dev/null -o /dev/null -r /dev/null app.js
service mongod restart
