#!/bin/bash
mkdir -p /var/www/vhosts/soludents/public/
cd /var/www/vhosts/soludents/public/frontend
npm install -unsafe-perm=true &> /dev/null
sleep 2m
npm start 
cd /var/www/vhosts/soludents/public/backend
npm install -unsafe-perm=true
sleep 2m
service mongod restart
